version: "2"
linters:
  default: none
  enable:
    - errcheck
    - errorlint
    - gocyclo
    - govet
    - lll
    - revive
    - staticcheck
  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false
    gocyclo:
      min-complexity: 30
    lll:
      line-length: 160
      tab-width: 1
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
